vich_uploader:
    db_driver: orm

    mappings:
        images:
            uri_prefix: /images
            upload_destination: '%kernel.project_dir%/public/images'
            # decided how uploaded files would be renamed
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        profile_pictures:
            uri_prefix: /profilePictures
            upload_destination: '%kernel.project_dir%/public/profilePictures'
            # decided how uploaded files would be renamed
            namer: Vich\UploaderBundle\Naming\UniqidNamer
